apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: stc
build:
  artifacts:
    - image: samcday/stc
      docker:
        dockerfile: Dockerfile
      hooks:
        before:
          - command: [./build.sh]
      runtimeType: go
manifests:
  helm:
    releases:
      - name: stc
        chartPath: chart
        setValues:
          config.leaderElection.leaderElect: false
          containerSpec:
            livenessProbe.initialDelaySeconds: 1
            readinessProbe.initialDelaySeconds: 1
        setValueTemplates:
          containerSpec:
            image: "{{.IMAGE_REPO_samcday_stc}}:{{.IMAGE_TAG_samcday_stc}}@{{.IMAGE_DIGEST_samcday_stc}}"
deploy:
  helm:
    hooks:
      before:
        - host:
            command: [ kubectl, apply, -f, chart/crds/stc.samcday.com_syncthingclusters.yaml, --server-side=true ]
profiles:
  - name: amd64
    patches:
      - op: add
        path: /manifests/helm/releases/0/setValues/nodeSelector.kubernetes\.io~1arch
        value: amd64
      - op: add
        path: /manifests/helm/releases/0/setValues/defaultCluster.spec.podSpec.nodeSelector.kubernetes\.io~1arch
        value: amd64
  - name: cluster
    patches:
      - op: add
        path: /manifests/helm/releases/0/setValues/defaultCluster
        value:
          enabled: true
          metadata.name: default
