apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stc.fullname" . }}
data:
  config.yaml: |-
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    {{- tpl (toYaml $.Values.config) $ | nindent 4 }}
