{{- if $.Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stc.serviceAccountName" $ }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "stc.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "stc.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "stc.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "stc.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "stc.serviceAccountName" $ }}
roleRef:
  kind: Role
  name: {{ include "stc.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
