apiVersion: stc.samcday.com/v1alpha1
kind: SyncthingCluster
metadata:
  labels:
    app.kubernetes.io/name: syncthingcluster
    app.kubernetes.io/instance: syncthingcluster-sample
    app.kubernetes.io/part-of: stc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: stc
  name: syncthingcluster-sample
spec:
  devices:
    XA6A6Y7-FDQFGUK-ZWWBP47-YBLYGIH-2D7W7SL-7ZO7NHR-RNMZ7GT-T65CMA6: {}
  podSpec:
    containers: []
    tolerations:
      - key: samcday.com/cloud
        effect: NoExecute
